# Generated by Django 6.0.5 on 2026-05-20 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bairro', models.CharField(blank=True, max_length=80)),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'db_table': 'relatos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bairro'], name='relatos_bairro_0fed70_idx'), models.Index(fields=['-created_at'], name='relatos_created_8c04a3_idx')],
            },
        ),
    ]
