# Generated by Django 6.0.5 on 2026-06-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatos', '0003_relato_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='relatos.relato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('relato', 'user')},
            },
        ),
    ]
