# Generated by Django 6.0.6 on 2026-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatos', '0005_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
