# Generated by Django 6.0.6 on 2026-06-07 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relatos', '0005_confirmacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('push', 'Push (app)')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('detalhe', models.TextField(blank=True, help_text='Erro ou ID externo do disparo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='relatos.relato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relato'], name='alertas_relato__9435ac_idx'), models.Index(fields=['usuario'], name='alertas_usuario_32b341_idx')],
                'unique_together': {('relato', 'usuario', 'canal')},
            },
        ),
    ]
